In [1]:
import torch

# 1. Set the device automatically
if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print(f"Using device: {device}")

# 2. Create a tensor and push it to your M1 GPU
x = torch.rand(3, 3)
x = x.to(device)

print("\nTensor successfully pushed to hardware:")
print(x)

Using device: mps

Tensor successfully pushed to hardware:
tensor([[0.8948, 0.9078, 0.4835],
        [0.6636, 0.6007, 0.3755],
        [0.7906, 0.0559, 0.5361]], device='mps:0')


In [15]:
import torch
import numpy as np

# LISTS:

In [42]:
my_list = [1, 2, 3, 4, 5]
print(my_list)

my_multi_list = [[1, 2, 3], [4, 5, 6]]
print(my_multi_list)

[1, 2, 3, 4, 5]
<class 'list'>
[[1, 2, 3], [4, 5, 6]]


# NUMPY ARRAY:

In [28]:
np1 = np.random.rand(3, 3)
print(np1)
print(np1.dtype)

[[0.41559857 0.76174002 0.81122729]
 [0.02690201 0.93449185 0.87664198]
 [0.19650119 0.63627586 0.43163023]]
float64


# TENSORS:

In [30]:
tensor_2d = torch.randn(3, 3)
print(tensor_2d)

tensor([[ 1.4207, -0.2393,  0.0342],
        [-0.0817, -2.3986,  0.3981],
        [ 0.5557, -0.0817,  0.3952]])


In [38]:
tensor_3d = torch.randn(2, 3, 4)
print(tensor_3d)
print(tensor_3d.dtype)

tensor([[[-0.7623, -1.2965, -1.2221, -1.5137],
         [-0.7973,  1.9302,  0.5862,  0.6370],
         [ 0.1078,  0.8610, -0.0280, -1.0659]],

        [[-0.5130,  0.5475,  0.2466,  0.5326],
         [ 2.4763,  0.4086, -0.7430,  0.8057],
         [ 0.2146, -0.4866,  0.6274, -0.0668]]])
torch.float32


In [35]:
### create tensor from numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4156, 0.7617, 0.8112],
        [0.0269, 0.9345, 0.8766],
        [0.1965, 0.6363, 0.4316]], dtype=torch.float64)

# Tensor Operations:

In [45]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# Reshape and View
my_torch2 = my_torch.reshape(2,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [53]:
#reshape with unknow number of items
my_torch3 = my_torch.reshape(2, -1)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [61]:
# shared mutable state
my_torch[0] = 314

print(my_torch)
print(my_torch2)
print(my_torch3)

my_torch number: 0
my_torch number: 1
my_torch number: 2
tensor([314,   1,   2,   3,   4,   5,   6,   7,   8,   9])
tensor([[314,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])
tensor([[314,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])


In [81]:
#Slices
my_torch4 = torch.arange(10)
print(my_torch4[1]) #grab single item
print(my_torch4[0:5]) #grab slice
print()

my_torch5 = my_torch4.reshape(5, 2)
print(my_torch5)
print()
print(my_torch5[:,0])

tensor(1)
tensor([0, 1, 2, 3, 4])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

tensor([0, 2, 4, 6, 8])
